"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['gui_wx.py']
DATA_FILES = []
OPTIONS = {'iconfile': True,
            'packages':['sympy', 'wxPython', 'engineering_notation']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
