"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import sys
from version import __version__
sys.setrecursionlimit(5000)

APP = ['gui_wx.py']
DATA_FILES = []
OPTIONS = {'iconfile': '/Users/Thomas/Programming/Python/Wing_projects/LaSolv_wx/LaSolv_icon.icns',
 'matplotlib_backends': 'wxagg',
 'plist': 'Info.plist'
    }

setup(
    app=APP,
    name='LaSolv',
    version=__version__,
    version_info=__version_info__,
    author='Thomas Spargo',
    author_email='taspargo@gmail.com',
    url='https://github.com/taspargo/Lasolv/',
    license="GNU GPL",
    data_files=DATA_FILES,
    options={'pyinstaller': OPTIONS},
    setup_requires=['pyinstaller'],
)
